services:

  postgres:
    image: postgres:18
    container_name: clinic-manager-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: clinic_manager
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: clinic

    ports:
      - "5434:5432"

    volumes:
      - clinic_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinic_user -d clinic_manager"]
      interval: 5s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: clinic-manager-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinicmanager.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "8081:80"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - clinic_pgadmin_data:/var/lib/pgadmin


volumes:
  clinic_postgres_data:
  clinic_pgadmin_data: